[network]
name = "testnet"

[accounts.deployer]
mnemonic = "avocado junk usage basic gaze vanish husband smooth slow cluster aunt vibrant noble palace blue bag picture describe garment predict spice woman collect impulse"